---
- name: Ceph cluster to run on a single host
  hosts: cephmonitor
  pre_tasks:
    - name: Save the contents of /etc/os-release
      command: cat /etc/os-release
      register: os_release
      changed_when: False
    - name: Detect Linux Servers
      debug:
        msg: "Find on CentOS|Fedora..."
      when: os_release.stdout.find('CentOS') != -1 or os_release.stdout.find('Fedora') != -1
      changed_when: False
    - name: Detect Linux Servers
      debug:
        msg: "Find on Debian|Ubuntu..."
      when: os_release.stdout.find('debian') != -1 or os_release.stdout.find('Ubuntu') != -1
      changed_when: False
  tasks:
    - name: Install cephadm 
      block:
      - name: Install cephadm
        become: true
        ansible.builtin.package:
          name: cephadm
          state: present
      rescue:
      - name: Install curl and python3
        become: true
        ansible.builtin.package:
          name: 
            - curl
            - python3
          state: present
      - name: Use curl to fetch standalone script cephadm
        become: true
        ansible.builtin.uri:
          url: https://github.com/ceph/ceph/raw/quincy/src/cephadm/cephadm
          method: GET
          dest: /usr/bin/cephadm
      - name: Chmod X cephadm
        become: true
        ansible.builtin.file:
          path: /usr/bin/cephadm
          owner: root
          group: root
          mode: "0755"
    # - name: Add-repo quincy
    #   become: true
    #   ansible.builtin.shell:  cephadm add-repo --release quincy
    #   ignore_errors: true
    # - name: Install ceph-common
    #   become: true
    #   ansible.builtin.shell:  cephadm install ceph-common
    - name: Bootstrap new single-host cluster
      become: true
      ansible.builtin.shell: cephadm bootstrap --mon-ip {{ FIRST_HOST_MONITOR }} --single-host-defaults --allow-fqdn-hostname
      register: bass_result
      failed_when:
        - bass_result.rc == 1
        - '"ERROR: /etc/ceph/ceph.conf already exists; delete or pass --allow-overwrite to overwrite" not in bass_result.stderr'
    - name: Deploy OSDs
      become: true
      ansible.builtin.shell: cephadm shell -- ceph orch apply osd --all-available-devices
    - name: Create pool for kube
      become: true
      ansible.builtin.shell: cephadm shell -- ceph osd pool create {{ POOL_NAME }} 10
    - name: Enable rbd in pool
      become: true
      ansible.builtin.shell: cephadm shell -- ceph osd pool application enable {{ POOL_NAME }} rbd
    - name: Create {{ CEPH_USER }}
      become: true
      ansible.builtin.shell: cephadm shell -- ceph auth get-or-create client.{{ CEPH_USER }} mon 'profile rbd' osd 'profile rbd pool=kube'
    - name: Get key {{ CEPH_USER }}
      become: true
      ansible.builtin.shell: cephadm shell -- ceph auth get-key client.{{ CEPH_USER }}
      register: ceph_userkey_id
      changed_when: False
    - name: catch ceph fsid
      become: true
      ansible.builtin.shell: cephadm shell -- ceph fsid
      register: ceph_cluster_id
      changed_when: False
    - name: catch ceph mon IP
      become: true
      ansible.builtin.shell: cephadm shell -- ceph mon dump
      register: ceph_cluster_ip
      changed_when: False
    - name: Print ceph fsid
      debug:
        var: ceph_cluster_id.stdout  
    - name: Print ceph IP
      debug:
        var: ceph_cluster_ip.stdout
    - name: Print key {{ CEPH_USER }}
      debug:
        var: ceph_userkey_id.stdout
